### ISSUE TITLE
Switching from 0.5.1.0 to 1.0.0.1 makes GHC hang forever

### ISSUE THREAD

**Issue by lortabac** [kcsongor/generic-lens#48] opened 2018-05-15 13:44 UTC
If I switch to `1.0.0.1` on a medium-sized code base that was using `0.5.1.0` the compilation does not terminate.

Unfortunately I cannot be more specific on the code that is causing non-termination. I tried commenting out functions one by one to locate the incriminated lines, and I found that the only way to make it compile is to remove all the functions that use `generic-lens`.

It happens in GHC whatever the `-O` level, and in GHCI too. If I build with `-v` I can see it gets stuck during the `Renamer/typechecker` phase.

I have already used `1.0.0.1` in small "toy" projects and I haven't had any issue. So I cannot exclude a bug in my code. However, whatever the reason of the problem, it is clearly related to `generic-lens`, so I think it is worth reporting it.

**Comment by kcsongor** [comment] 2018-05-15 13:47
Thanks, definitely worth reporting. Would it be possible to strip out some of the code so that I could reproduce and fix this? I've not come across this before

**Comment by lortabac** [comment] 2018-05-15 15:29
Unfortunately I cannot reproduce this issue outside of this particular code base. I will post some code if I succeed.

For the moment all I can say is that the code base includes several big records (>20 fields), sharing a lot of field names. And most of the code that uses `generic-lens` consists of just copying fields from one record to another. There is nothing too fancy except the size of some records.

**Comment by arianvp** [comment] 2018-05-17 10:40
Is there also an explosive amount of memory usage in that phase? We have been experiencing
similar issues in our generic library with datatype that have lots of records and constructors

https://github.com/VictorCMiraldo/generics-mrsop/issues/6

**Comment by kcsongor** [comment] 2018-05-17 10:46
Sadly I've not managed to reproduce the issue. I did make an effort to optimise compile times, but there's also a possibility that the algorithm hangs for certain cases I've not yet come across. I also have tested 20+ records and sums, and seemed to work fine

**Comment by kcsongor** [comment] 2018-05-17 10:48
@lortabac it would be useful to know which version of GHC you're using too

**Comment by lortabac** [comment] 2018-05-22 07:31
@arianvp Memory usage seems to increase over time but I would not call it explosive. In the OS monitoring tool I see it go up at intervals of several minutes.

@kcsongor I am using GHC 8.2.1.

**Comment by kcsongor** [comment] 2018-05-22 08:04
aha! there’s a bug in 8.2.1 which results in exactly this. Is it possible for you to try 8.2.2?

**Comment by lortabac** [comment] 2018-05-22 08:32
I have the same issue on 8.2.2.

**Comment by kcsongor** [comment] 2018-08-08 13:29
This might have been caused by a compile-time performance regression that I now believe is fixed. I recognise this was a while ago, but would you be able to try with 1.0.0.2?

**Comment by lortabac** [comment] 2018-08-08 14:08
Yes. It compiles with 1.0.0.2. Thanks!

**Comment by kcsongor** [comment] 2018-08-08 14:09
Brilliant! Is the compile-time tolerable now?

**Comment by kcsongor** [comment] 2018-08-08 14:14
Thanks, I'll close the issue then

**Closed by kcsongor** 2018-08-08 14:14 UTC
